services:
  - type: web
    name: phishing-url-detector
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -w 1 -b 0.0.0.0:10000 src.app:app"
    envVars:
      PYTHON_VERSION: 3.10

